### ISSUE TITLE
Join dataset - able to share?

### ISSUE THREAD

**Issue by NickJewell** [dorianb96/apache-spark-vs-pandas-benchmark#1]
Hi Dorian,

Great job on putting this together. One small request - what's the contents of the Join dataset that you use for Scenario 3 please?

Cheers,
Nick

**Comment by dorianbg** [comment]
Hi Nick,

Sorry for this, I totally forgot to upload atleast a part of the data.

But I used a small dataset, made of distinct types of cars from the original dataset. 

Now I've uploaded it to github under the join_data.csv filename.
